DROP TABLE IF EXISTS items_in_order CASCADE;

CREATE TABLE items_in_order (
  id SERIAL PRIMARY KEY NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 0,
  order_id INTEGER REFERENCES orders(id) ON DELETE CASCADE,
  item_id INTEGER REFERENCES items(id) ON DELETE CASCADE
);
